### ISSUE TITLE
DesktopGL Support

### ISSUE THREAD

**Issue by ianhattendorf** [discosultan/quake-console#6] opened 2016-04-28 23:57 UTC
Any plans to support more than WindowsDX?

**Comment by discosultan** [comment] 2016-04-29 07:57
This has also been requested before so I will probably take a look at it sometime soon. 

There shouldn't be any showstoppers since only the embedded effect needs to be recompiled for OpenGL. There's just the overhead of having to manage multiple projects/build configurations for multiple platforms.

**Comment by ianhattendorf** [comment] 2016-04-29 15:26
Sounds good, I might be able to take a look at it in the near future as well if I get some free time. I'm not sure how you're handling building and publishing to nuget right now, but there are ways you can automate your build and deploy that would certainly help.

**Comment by discosultan** [comment] 2016-05-03 15:56
I've made available QuakeConsole and PythonInterpreter for DesktopGL through Nuget:
[MonoGame.QuakeConsole.DesktopGL](https://www.nuget.org/packages/MonoGame.QuakeConsole.DesktopGL/)
[MonoGame.QuakeConsole.PythonInterpreter.DesktopGL](https://www.nuget.org/packages/MonoGame.QuakeConsole.PythonInterpreter.DesktopGL/)

Source code now contains separate solution and project files for WindowsDX and DesktopGL platforms.

**Note that I have not tested this running on Mono!**

**Comment by ianhattendorf** [comment] 2016-05-03 16:46
Great, I'll take a look later today.

One thing I noticed is that some of the projects are targeted for x86 instead of AnyCPU. Any particular reason for this? This locks anyone using these packages to x86 as well.

**Comment by discosultan** [comment] 2016-05-03 16:51
Only because MonoGame project template defaulted to x86. I can't think of any reason why it can't be AnyCPU instead. Will change this at some point.

**Comment by ianhattendorf** [comment] 2016-05-07 05:20
Awesome, everything is running great on Windows. I ran into 2 issues with the Python Interpreter while running on OS X, mono v4.2.3.4.

1. Occasionally, ParamInfos are null here:
https://github.com/discosultan/quake-console/blob/master/Interpreters/PythonInterpreter/TypeLoader.cs#L132
Adding `if (memberInfo.ParamInfos[i] == null) continue;` fixes this, however I don't know if there's another issue this is ignoring.

2. For some reason it's trying to `from System import Int32&` which is throwing an exception due to trying to import the type name with the '&' reference at the end. Adding `.TrimEnd('&')` after type.Name here:
https://github.com/discosultan/quake-console/blob/master/Interpreters/PythonInterpreter/TypeLoader.cs#L154
fixes this, however again this seams like it's just hiding another issue.

Any ideas? I could submit a PR with those fixes however I'm not sure that's the best course of action.

**Comment by discosultan** [comment] 2016-05-07 08:25
Thanks for testing on Mono!

1. Seems to be an interesting issue to do with the combination of using null propagation with extension method (a bug in Mono?). The code snippet ```memberInfo.ParamInfos[i]?.ForEach``` should fulfill the same purpose as ```if (memberInfo.ParamInfos[i] != null) memberInfo.ParamInfos[i].ForEach``` but that doesn't seem to be the case. I suspect due to the fact that ```ForEach``` is defined as an extension method [here](https://github.com/discosultan/quake-console/blob/master/Interpreters/PythonInterpreter/Utilities.cs#L72-L76). It's a very minor syntactic sugar thing and the extension method should probably be removed altogether if it causes such issues.

2. Seems to be a subtle difference in the type system. The & symbol most probably defines a reference type (in your case, a pass by ref int). Easiest course of action is to simply trim the symbol like you suggested. That should functionally behave as expected, it's just that the types might be loaded twice in that case (for example, once for regular *Int32* and once for *Int32&*). That shouldn't be an issue, though.

I've also added the Python interpreter unit tests project for DesktopGL sln. I'll see if I can somehow use Visual Studio to build the tests using XBuild targeting Mono assemblies.

**Comment by ianhattendorf** [comment] 2016-05-07 21:35
I ran into the issue when adding the `GraphicsDeviceManager` as a variable. I also ran into the issue with a class I created with the property `public bool Enabled { get; set; } = true;` trying to load a `Boolean&`.

It could be unique to OS X and possibly Linux, are you testing on Windows?

**Comment by discosultan** [comment] 2016-05-08 12:28
I'm testing on Windows. I'll take another shot at it tomorrow and if am unable to reproduce then I'll simply trim the ampersand from type name as you suggested.

**Comment by discosultan** [comment] 2020-08-17 16:40
Closing since supported. Has not been tested on other platforms than Windows though.

**Closed by discosultan** 2020-08-17 16:40 UTC
Labels: enhancement
